### ISSUE TITLE
Nokia Debloater bug report

### ISSUE THREAD

**Issue by KelvinCrag** [thanuj10/Nokia-Debloater#11]
Bugs found:
1. 'adb shell cmd install-existing --user 0' instead of 'adb shell cmd package install-existing --user 0'
2. 'goto Reboot Menu' instead of 'goto Reboot Options'

Fix: [batch-script_fixed.txt](https://github.com/thanuj10/Nokia-Debloater/files/4579614/batch-script_fixed.txt)

**EDIT**: Thanks for providing Nokia devices this script. Note that my only motives for filing these issues is to ensure that script is bugless.

**Comment by thanuj10** [comment]
Fixed these bugs and hence closing.
Thanks for your input.

**Comment by KelvinCrag** [comment]
> Fixed these bugs and hence closing.
> Thanks for your input.

No you didn't 🙄
The rebloating bug is still present. Adding .exe to the rebloat code doesn't change anything.
You were supposed to include `package` in code as I mentioned earlier, if not if you try to run rebloat script it won't work you'll just get an error code like `can't find install-existing` because it's taking install-existing as package and there’s no android application with that name tag.

PS there's a new bug found, in the last debloat list: `com.gti.qualcomm.datastatusnotification` instead of `com.qti.qualcomm.datastatusnotification`
And in rebloat section, after the 'rebloating is finished, press any key to reboot' note, there's no `pause` code so...
